name: aevitas-web

static_sites:
  - name: frontend
    environment_slug: html
    github:
      repo: phantasmagoriadigital/two_digital
      branch: main
      deploy_on_push: true
    source_dir: build
    index_document: index.html
    error_document: error.html
    routes:
      - path: /
